services:
  postgres:
    image: postgres:15-alpine3.19
    container_name: fastapi_pgdata
    ports:
    - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=250'

  k8s-handler:
    image: k8s-handler:latest
    container_name: k8s-handler
    build:
      context: .
      dockerfile: docker/dev/dockerfile
    volumes:
      - ~/.kube/config:/root/.kube/config
      - .:/home/app    
  
  alembic:
    image: k8s-handler-migrations:latest
    container_name: k8s-handler-migration
    build:
      context: .
      dockerfile: docker/alembic/dockerfile
    env_file:
      - .env
    volumes:
      - .:/home/app
    depends_on:
      - postgres